name: pg-fingerprint-action
description: Given a list of sql files, checks if their AST's fingerprints remain unchanged in a PR. For internal use.
author: helpwave

# Define your inputs here.
inputs:
  files:
    description: 'Which files to check. A JSON string array.'
    required: true

runs:
  using: node20
  main: dist/index.js
